/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authAuthIndexImport } from './routes/(auth)/_auth.index'

// Create/Update Routes

const authAuthIndexRoute = authAuthIndexImport.update({
  id: '/(auth)/_auth/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth/': {
      id: '/(auth)/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof authAuthIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)/_auth/': typeof authAuthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(auth)/_auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authAuthIndexRoute: typeof authAuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  authAuthIndexRoute: authAuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)/_auth/"
      ]
    },
    "/(auth)/_auth/": {
      "filePath": "(auth)/_auth.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
